### ISSUE TITLE
le ping ne marche pas bien

### ISSUE THREAD

**Issue by Jules-Latapy** [LotharieSlayer/wtpbot#85]
https://github.com/LotharieSlayer/wtpbot/blob/eb9e89e1b8af2d38abed770fff8224b6e83b359d/src/commands/other/ping.js#L31

il faut inverser la soustraction !!

**Comment by LotharieSlayer** [comment]
oui je sais........................

**Comment by LotharieSlayer** [comment]
https://github.com/LotharieSlayer/wtpbot/pull/84
